version: "3"

services:

  memory_commander:

    image: ghcr.io/joeferner/redis-commander:latest

    ports:

      - ${MEMORY_COMMANDER_PORT}:8081

    restart: always

    environment:

      TZ: ${TZ}

      REDIS_HOST: memory
      REDIS_PASSWORD_FILE: /run/secrets/memory
      HTTP_USER: ${DATABASE_USERNAME}
      HTTP_PASSWORD_FILE: /run/secrets/memory

    secrets:

      - memory

    depends_on:

      - memory

  database_postgresql_pgadmin:

    image: dpage/pgadmin4:latest

    volumes:

      - ./storage/postgresql/servers.json:/pgadmin4/servers.json

    ports:

      - ${DATABASE_POSTGRESQL_PGADMIN_PORT}:80

    restart: always

    environment:

      TZ: ${TZ}

      PGADMIN_DEFAULT_EMAIL: ${DATABASE_EMAIL}
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/database_postgresql

    secrets:

      - database_postgresql

    depends_on:

      - database_postgresql
