version: "3"

services:

  nginx:

    image: "nginx:1.23.3-alpine"
    container_name: "nginx"

    volumes:

      # - "./*.conf:/etc/nginx/conf.d/default.conf" #

      - "./log_error:/var/www/nginx/error_log"
      - "./log_access:/var/www/nginx/access_log"
      - "../none.html:/var/www/nginx/none.html"
      - "../index.html:/var/www/nginx/index.html"

    ports:

      - "8000:80"

    # entrypoint: [] #
    # command: ["tail", "-f", "/dev/null"] #
