version: "3"

services:

  httpd:

    image: "httpd:2.4.54-alpine"
    container_name: "httpd"

    volumes:

      # - "./*.conf:/usr/local/apache2/conf/extra/default.conf" #

      - "./log_error:/var/www/httpd/error_log"
      - "./log_access:/var/www/httpd/access_log"
      - "../none.html:/var/www/httpd/none.html"
      - "../index.html:/var/www/httpd/index.html"

    ports:

      - "8000:80"

    # entrypoint: [] #
    command: >
      sh -c "sed -i'.bak' 's/\#Include conf\/extra\/httpd-vhosts\.conf/Include conf\/extra\/default\.conf/g' /usr/local/apache2/conf/httpd.conf
      && httpd-foreground"
